openapi: 3.0.1

info:
  title: ecoMobility - Treecko API
  description: API documentation for ecoMobility release v1.0 Treecko.
  version: 1.0.0
  contact:
    name: Mail
    email: ecomobilityupc@gmail.com

servers:
  - url: http://localhost:3000/api/v1/
    description: API v1.0
tags:
  - name: Estaciones
    description: Endpoints para estaciones

paths:
  /estaciones:
    get:
      tags:
        - Estaciones
      summary: Obtener todas las estaciones
      description: Obtener todas las estaciones de la DB con todos sus atributos.
      operationId: getAllEstaciones
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Estacion"
        204:
          description: "No content"
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/204"
    post:
      tags:
        - Estaciones
      summary: Crear una nueva estación.
      description: Crear una nueva estación en la DB con los atributos especificados.
      operationId: postEstacion
      parameters:
        - name: ADREÇA
          in: query
          description: Dirección donde se encuentra la nueva estación de carga.
          required: true
          explode: false
          schema:
            type: string
        - name: LATITUD
          in: query
          description: Latitud donde se encuentra la nueva estación de carga.
          required: true
          explode: false
          schema:
            type: string
        - name: LONGITUD
          in: query
          description: Longitud donde se encuentra la nueva estación de carga.
          required: true
          explode: false
          schema:
            type: string
        - name: MUNICIPI
          in: query
          description: Municipio donde se encuentra la nueva estación de carga.
          required: true
          explode: false
          schema:
            type: string
        - name: PROVINCIA
          in: query
          description: Provincia donde se encuentra la nueva estación de carga.
          required: true
          explode: false
          schema:
            type: string
            enum:
              - Barcelona
              - Tarragona
              - Lleida
              - Girona
        - name: CODIPROV
          in: query
          description: Código identificador de la provincia donde se encuentra la nueva estación de carga.
          required: true
          explode: false
          schema:
            type: string
        - name: TIPUS DE CORRENT
          in: query
          description: Tipo de corriente de la que dispone la nueva estación de carga.
          required: false
          explode: false
          schema:
            type: string
            enum:
              - AC
              - DC
              - AC-DC
        - name: TIPUS VELOCITAT
          in: query
          description: Tipo de velocidad de carga de la que dispone la nueva estación de carga.
          required: false
          explode: false
          schema:
            type: string
            enum:
              - RAPID
              - semiRAPID
              - NORMAL
              - RAPID
              - RAPID i NORMAL
              - RAPID i semiRAPID
              - semiRAPID i NORMAL
              - superRAPID
        - name: TIPUS VEHICLE
          in: query
          description: Tipos de vehiculos que pueden cargarse en la nueva estación de carga.
          required: false
          explode: false
          schema:
            type: string
            enum:
              - mercaderies
              - cotxe
              - moto
              - moto i cotxe
              - taxi
        - name: TIPUS CONNEXIÓ
          in: query
          description: Tipo de carga de la que dispone la nueva estación de carga.
          required: false
          explode: false
          schema:
            type: string
        - name: PROMOTOR-GESTOR
          in: query
          description: Entidad promotora o gestora de la nueva estación de carga.
          required: false
          explode: false
          schema:
            type: string
        - name: POTENCIA
          in: query
          description: Potencia en kW de la nueva estación de carga.
          required: false
          explode: false
          schema:
            type: string
        - name: NPLACES ESTACIÓ
          in: query
          description: Número de plazas de las que dispone la nueva estación de carga.
          required: false
          explode: false
          schema:
            type: string

      responses:
        201:
          description: Estación created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Estacion"
        400:
          description: Bad request
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/400"

  /estaciones/direccion:
    get:
      tags:
        - Estaciones
      summary: Obtener la dirección de todas las estaciones
      description: Obtener los atributos DIRECCION y ID de todas las estaciones de la DB.
      operationId: getDirAllEstaciones
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DirEstacion"
        204:
          description: "No content"
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/204"

  /estaciones/coordenadas:
    get:
      tags:
        - Estaciones
      summary: Obtener las coordenadas de todas las estaciones
      description: Obtener los atributos LONGITUD, LATITUD y ID de todas las estaciones de la DB.
      operationId: getCoordAllEstaciones
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CoordEstacion"
        204:
          description: "No content"
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/204"

  /estaciones/{ID}:
    get:
      tags:
        - Estaciones
      summary: Obtener una estacion concreta
      description: Obtener todos los atributos de la estacion especificada en el path.
      operationId: getEstacion
      parameters:
        - name: ID
          in: path
          description: Identificador de la estación que queremos consultar
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Estacion"
        204:
          description: "No content"
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/204"
        400:
          description: Bad request
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/400"
        404:
          description: Not found
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/404"
    put:
      tags:
        - Estaciones
      summary: Actualizar una nueva estación.
      description: Actualiza la estacion definida en el path añadiendo los atributos especificados en el body.
      operationId: updateEstacion
      parameters:
        - name: ID
          in: path
          description: Identificador de la estación que queremos actualizar
          required: true
          schema:
            type: string
        - name: ADREÇA
          in: query
          description: Dirección donde se encontrará la estación de carga actualizada.
          required: false
          explode: false
          schema:
            type: string
        - name: LATITUD
          in: query
          description: Latitud donde se encontrará la estación de carga actualizada.
          required: false
          explode: false
          schema:
            type: string
        - name: LONGITUD
          in: query
          description: Longitud donde se encontrará la estación de carga actualizada.
          required: false
          explode: false
          schema:
            type: string
        - name: MUNICIPI
          in: query
          description: Municipio donde se encontrará la estación de carga actualizada.
          required: false
          explode: false
          schema:
            type: string
        - name: PROVINCIA
          in: query
          description: Provincia donde se encontrará la estación de carga actualizada.
          required: false
          explode: false
          schema:
            type: string
            enum:
              - Barcelona
              - Tarragona
              - Lleida
              - Girona
        - name: CODIPROV
          in: query
          description: Código identificador de la provincia donde se encontrará la estación de carga actualizada.
          required: false
          explode: false
          schema:
            type: string
        - name: TIPUS DE CORRENT
          in: query
          description: Tipo de corriente de la que dispondrá la estación de carga actualizada.
          required: false
          explode: false
          schema:
            type: string
            enum:
              - AC
              - DC
              - AC-DC
        - name: TIPUS VELOCITAT
          in: query
          description: Tipo de velocidad de carga de la que dispondrá la estación de carga actualizada.
          required: false
          explode: false
          schema:
            type: string
            enum:
              - RAPID
              - semiRAPID
              - NORMAL
              - RAPID
              - RAPID i NORMAL
              - RAPID i semiRAPID
              - semiRAPID i NORMAL
              - superRAPID
        - name: TIPUS VEHICLE
          in: query
          description: Tipos de vehiculos que podrán cargarse en la estación de carga actualizada.
          required: false
          explode: false
          schema:
            type: string
            enum:
              - mercaderies
              - cotxe
              - moto
              - moto i cotxe
              - taxi
        - name: TIPUS CONNEXIÓ
          in: query
          description: Tipo de carga de la que dispondrá la estación de carga actualizada.
          required: false
          explode: false
          schema:
            type: string
        - name: PROMOTOR-GESTOR
          in: query
          description: Entidad promotora o gestora de la estación de carga actualizada.
          required: false
          explode: false
          schema:
            type: string
        - name: POTENCIA
          in: query
          description: Potencia en kW de la estación de carga actualizada.
          required: false
          explode: false
          schema:
            type: string
        - name: NPLACES ESTACIÓ
          in: query
          description: Número de plazas de las que contará la estación de carga actualizada.
          required: false
          explode: false
          schema:
            type: integer

      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/examples/200Update"
        400:
          description: Bad request
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/400"
        404:
          description: Bad request
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/404"
    delete:
      tags:
        - Estaciones
      summary: Eliminar una estacion concreta
      description: Eliminar la estacion especificada en el path.
      operationId: deleteEstacion
      parameters:
        - name: ID
          in: path
          description: Identificador de la estación que queremos eliminar
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/examples/200Delete"
        404:
          description: Not found
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/404"

  /estaciones/{ID}/direccion:
    get:
      tags:
        - Estaciones
      summary: Obtener la direccion de una estacion concreta
      description: Obtener los atributos DIRECCION y ID de la estacion especificada en el path.
      operationId: getDirEstacion
      parameters:
        - name: ID
          in: path
          description: Identificador de la estación que queremos consultar
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DirEstacion"
        204:
          description: "No content"
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/204"
        400:
          description: Bad request
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/400"
        404:
          description: Not found
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/404"

  /estaciones/{ID}/coordenadas:
    get:
      tags:
        - Estaciones
      summary: Obtener las coordenadas de una estacion concreta
      description: Obtener los atributos LONGITUD, LATITUD y ID de la estacion especificada en el path.
      operationId: getCoordEstacion
      parameters:
        - name: ID
          in: path
          description: Identificador de la estación que queremos consultar
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CoordEstacion"
        204:
          description: "No content"
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/204"
        400:
          description: Bad request
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/400"
        404:
          description: Not found
          content:
            application/json:
              examples:
                example:
                  $ref: "#/components/examples/404"

components:
  schemas:
    Estacion:
      type: object
      properties:
        ID:
          type: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        ADREÇA:
          type: string
          example: "Avinguda Meridiana, 66"
        CODIPROV:
          type: string
          example: "08"
        LATITUD:
          type: string
          example: "41.74441"
        LONGITUD:
          type: string
          example: "2.18729"
        MUNICIPI:
          type: string
          example: "Barcelona"
        NPLACES ESTACIÓ:
          type: integer
          format: int64
          example: 3
        POTENCIA:
          type: string
          example: "22"
        PROMOTOR-GESTOR:
          type: string
          example: "Generalitat de Catalunya"
        PROVINCIA:
          type: string
          example: "Barcelona"
          enum:
            - Tarragona
            - Girona
            - Barcelona
            - Lleida
        TIPUS CONNEXIÓ:
          type: string
          example: "2xMENNEKES.F"
        TIPUS DE CORRENT:
          type: string
          example: "AC"
          enum:
            - AC
            - DC
            - AC-DC
        TIPUS VEHICLE:
          type: string
          example: "cotxe i moto"
          enum:
            - mercaderies
            - cotxe
            - moto
            - moto i cotxe
            - taxi
        TIPUS VELOCITAT:
          type: string
          example: "semiRAPID"
          enum:
            - RAPID
            - semiRAPID
            - NORMAL
            - RAPID
            - RAPID i NORMAL
            - RAPID i semiRAPID
            - semiRAPID i NORMAL
            - superRAPID

    CoordEstacion:
      type: object
      properties:
        ID:
          type: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        LATITUD:
          type: string
          example: "41.74441"
        LONGITUD:
          type: string
          example: "2.18729"

    DirEstacion:
      type: object
      properties:
        ID:
          type: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        ADREÇA:
          type: string
          example: "Avinguda Meridiana, 66"

  examples:
    204:
      value:
        status: 204
        error: "No content"
        message: "No content"
    200Update:
      value:
        status: 200
        error: "Successful operation"
        message: "Successful update"
    200Delete:
      value:
        status: 200
        error: "Successful operation"
        message: "Successful delete"
    400:
      value:
        status: 400
        error: "Bad request"
        message: "Missing attributes"
    404:
      value:
        status: 404
        error: "Not found"
        message: "ID does not exist"
